Header header

# Travel pules for each wheel, /90 equals number of tire turns
int32 left_front_travel
int32 right_front_travel
int32 left_rear_travel
int32 right_rear_travel

# Travel speed for each wheel, in m/s
float64 left_front_speed
float64 right_front_speed
float64 left_rear_speed
float64 right_rear_speed

# Turn angle for each wheel, in degree
float64 left_front_angle
float64 right_front_angle
float64 left_rear_angle
float64 right_rear_angle
